version: '3.2'

services:
  downloader:
    build: .
    restart: on-failure
    command: yarn watch
    env_file: .env
    volumes:
      - /workspace/node_modules
      - .:/workspace
      - E:/offcloud/watch:/watch
      - E:/offcloud/download:/download